
include .\includes\incs\base.inc
include .\includes\incs\blur.inc
;include .\includes\incs\fade.inc
include .\includes\incs\matrix.inc
include .\includes\incs\video.inc
include .\includes\incs\vesainit.inc
include .\includes\incs\serv\segwork.inc

include .\includes\incs\2d\bump.def
include .\includes\incs\2d\bump.inc

include 3d.inc

include .\includes\incs\serv\sin.inc

include .\includes\incs\3d\sort.inc
include .\includes\incs\3d\normal.inc
include .\includes\incs\3d\camera.inc

include .\includes\incs\poly_4\poly.def

include .\includes\incs\poly_4\tmp.inc
include .\includes\incs\poly_4\tmp2.inc
include .\includes\incs\poly_4\tmp3.inc
include .\includes\incs\poly_4\poly.inc

include .\includes\incs\2d\sprites.in3

include .\includes\incs\serv\events.inc


include alph_obj.inc

include part0.inc
include part1.inc
include part3.inc
include part4.inc
include part5.inc
include part6.inc
include part7.inc
include part8.inc

include ev_proc.inc

include serv.inc

include objects.inc


include .\includes\incs\font\font_out.inc
include .\includes\incs\font\unp_rle.in3

include .\includes\incs\2d\flare.inc
include .\includes\incs\2d\draw_flr.in3

include .\includes\incs\2d\font_ou2.def
include .\includes\incs\2d\font_ou2.inc
include .\includes\incs\2d\table.def
include .\includes\incs\2d\table2.inc

include f:\dem\common\incs\texgen2\texgen.inc

include .\includes\incs\objge3__\obj.inc

include text2.inc

;include particl1.inc

include serv2.inc

include particle.inc

AA_FONT_X_SIZE  equ 32
AA_FONT_Y_SIZE  equ 37
AA_ALL_FONT_X_SIZE equ 800 ;AA_FONT_X_SIZE*26
;Extrn Packed_AA_Font1_Sprite:near
;Extrn AA_Font1_Sprite:near
include .\includes\incs\font\font4__.inc

include .\includes\incs\font\unp_rle.in2

include .\includes\incs\font\font_out.in2

include .\includes\incs\meta\metaball.def
include .\includes\incs\meta\metaball.inc

include player.inc
.DATA
include .\includes\incs\meta\metatab.inc
include .\includes\data\sprite1.in2
include .\includes\data\man1.inc
include .\includes\data\man2.inc
include .\includes\data\font_c.inc

include ee.inc