.DATA

Text_1_2:
      db DESERT_COM,TX1,2
      db DESERT_COM,TX2,5

      db COLOR_COM,TX2,90,80,60
      db COLOR_COM,TX1,80,60,100

      db ALPHA2_COM,TX1,TX2,10,10

      db BLUR_COM,TX1
      db BLUR_COM,TX1


      db END_COM,TX1

Text_1_1:
      db DESERT_COM,TX1,2
      db DESERT_COM,TX2,5

      db COLOR_COM,TX2,90,50,30
      db COLOR_COM,TX1,60,60,70

      db ALPHA2_COM,TX1,TX2,10,10

      db BLUR_COM,TX1
      db BLUR_COM,TX1


      db END_COM,TX1

Lightmap3:
      db PHONG1_COM,TX1

      db COLOR_COM,TX1,100,55,22

      db BLUR_COM,TX1
      db BLUR_COM,TX1

      db END_COM,TX1

Lightmap1:
      db PHONG1_COM,TX1

      db BLUR_COM,TX1

;      db COLOR_COM,TX1,100,100,0

      db END_COM,TX1


Text4_1:
      db DESERT_COM,TX1,2
      db DESERT_COM,TX2,-1
      db ALPHA_COM,TX1,TX2,50

      db BLUR_COM,TX1
      db BLUR_COM,TX1

      db COLOR_COM,TX1,30,70,100

;      db COLOR_COM,TX1,10,40,60

;      db INV_COL_COM,TX1

      db END_COM,TX1

Text4_2:
      db DESERT_COM,TX1,2
      db DESERT_COM,TX2,5

;      db COLOR_COM,TX2,70,20,20
 ;     db COLOR_COM,TX1,100,30,20

      db COLOR_COM,TX2,75,25,20
      db COLOR_COM,TX1,100,35,20

      db ALPHA2_COM,TX1,TX2,20,30

      db BLUR_COM,TX1
      db BLUR_COM,TX1


      db END_COM,TX1

Text4_1_2:
      db DESERT_COM,TX1,2
      db DESERT_COM,TX2,-1
      db ALPHA_COM,TX1,TX2,50

      db BLUR_COM,TX1
      db BLUR_COM,TX1

      db COLOR_COM,TX1,10,40,60

;      db COLOR_COM,TX1,10,40,60

;      db INV_COL_COM,TX1

      db END_COM,TX1

Lightmap4:
      db PHONG1_COM,TX1

      db COLOR_COM,TX1,40,50,100

      db BLUR_COM,TX1
      db BLUR_COM,TX1

      db END_COM,TX1
